name: HonnyCompass
version: '${project.version}'
main: honny.HonnyCompass
authors:
  - honnisha
  - Yovez
description: "A plugin created by honnisha to display a compass to highlight targets for BetonQuest. Updated by Yovez"
api-version: 1.28

depend:
  - BetonQuest

softdepend:
  - PlaceholderAPI
  - AuthMe

commands:
  honnycompass:
    usage: '§e/honnycompass'
    aliases: [ hcompass ]